# Generated by Django 5.2.7 on 2026-02-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstagramUser",
            fields=[
                (
                    "user_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "FEMALE"),
                            ("Male", "MALE"),
                            ("Non-binary", "NON-BINARY"),
                            ("Prefer not to say", "PREFER NOT TO SAY"),
                        ],
                        max_length=20,
                        verbose_name="Genre",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Pays")),
                (
                    "income_level",
                    models.CharField(
                        choices=[
                            ("Low", "LOW"),
                            ("Middle", "MIDDLE"),
                            ("Upper-middle", "UPPER-MIDDLE"),
                            ("High", "HIGH"),
                        ],
                        max_length=50,
                        verbose_name="Niveau de revenu",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("Freelancer", "FREELANCER"),
                            ("Full-time employed", "FULL-TIME EMPLOYED"),
                            ("student", "STUDENT"),
                            ("Unemployed", "UNEMPLOYED"),
                            ("Part-time", "PART-TIME"),
                            ("Retired", "RETIRED"),
                        ],
                        max_length=50,
                        verbose_name="Statut d'emploi",
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("Single", "SINGLE"),
                            ("Divorced", "DIVORCED"),
                            ("Married", "MARRIED"),
                            ("Widowed", "WIDOWED"),
                            ("In a relationship", "IN A RELATIONSHIP"),
                        ],
                        max_length=50,
                        verbose_name="Statut relationnel",
                    ),
                ),
                ("has_children", models.BooleanField(verbose_name="A des enfants")),
                (
                    "weekly_work_hours",
                    models.IntegerField(verbose_name="Heures de travail par semaine"),
                ),
                (
                    "social_events_per_month",
                    models.IntegerField(verbose_name="Événements sociaux par mois"),
                ),
                (
                    "books_read_per_year",
                    models.IntegerField(verbose_name="Livres lus par an"),
                ),
                (
                    "posts_created_per_week",
                    models.IntegerField(verbose_name="Publications créées par semaine"),
                ),
                (
                    "followers_count",
                    models.IntegerField(verbose_name="Nombre de followers"),
                ),
                (
                    "account_creation_year",
                    models.IntegerField(verbose_name="Année de création du compte"),
                ),
                (
                    "content_type_preference",
                    models.CharField(
                        choices=[
                            ("Photos", "PHOTOS"),
                            ("Videos", "VIDEOS"),
                            ("Live", "LIVE"),
                            ("Mixed", "MIXED"),
                            ("Reels", "REELS"),
                        ],
                        max_length=100,
                        verbose_name="Préférence de type de contenu",
                    ),
                ),
                (
                    "preferred_content_theme",
                    models.CharField(
                        max_length=100, verbose_name="Thème préféré du contenu"
                    ),
                ),
                (
                    "privacy_setting_level",
                    models.CharField(
                        choices=[
                            ("Public", "PUBLIC"),
                            ("Friends Only", "FRIENDS ONLY"),
                            ("Private", "PRIVATE"),
                        ],
                        max_length=50,
                        verbose_name="Niveau des paramètres de confidentialité",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("Free", "FREE"),
                            ("Premium", "PREMIUM"),
                            ("Business", "BUSINESS"),
                        ],
                        max_length=50,
                        verbose_name="Statut d'abonnement",
                    ),
                ),
            ],
        ),
    ]
