# Generated by Django 5.2.7 on 2026-02-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='has_children',
            field=models.CharField(choices=[('no', 'NO'), ('yes', 'YES')], max_length=10, verbose_name='A des enfants'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='weekly_work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Heures de travail par semaine'),
        ),
    ]
